# Site settings
title: Machine Vision Lab
SEOTitle: 机器视觉实验室 | Machine Vision Lab
university: Fudan University
header-img: img/bg.jpg
theme-color: "#000000"
email: honglu@fudan.edu.cn
description: "This is a official website of Fudan Machine Vision Lab."
keyword: "Fudan, Machine Vision, Hong Lu"
url: "https://fudanmv.github.io"

# Build settings
permalink: pretty
paginate: 10
exclude: [ "less","node_modules","Gruntfile.js","package.json","README.md" ]

# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [ jekyll-paginate ]